name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5072ff4180e318241266c39c0370b35b13ee6da4dd18b7fbd422649665ba76d9"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
