name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad0c666112c88fc961bf8cc61a1afd93ec25ed00c5f1991e952dececc736a3e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
