name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45dfb756dc3a3315df526fec39d3918815434e974ad0b88d8da3c8c5635d1048"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
