name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22571e7f1da8274f3c236d634469bd4b8507a77b11d3b7451c7a5aa25dbbf3b1"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
