name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc58f06ebbb14e3c39758615cd9097325a2941d780b2e9fca2811354925c5a16"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
