name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4fc01d358d2cdf1fe593bf208c060675c80a889760da5ee5db73760616335a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
