name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ec8742fd00b1982a0836f683aa78327e310b260d3d92ed70f723498cdf39599"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
