name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f350513a24486d57ecf1eccebc7b1fd5454350e80d279404cbcd9e25fb1f5b63"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
