name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faa15e9d6bfd01fa3d69a8d9056dbc5ea11769c847594ec6d0c25f230bcb3613"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
