name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c049a3091d5dc821391c4bb341cd2cb3280e97ece6cae0d2cc895abedd89806e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
