name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f93e7fb724f0af1dfe961e1419ff2094e4aeffddb1910a45dcd25c87e268b8f"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
