name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ced4b127eeda787be2a83aa57e9bc8f8b55482473751866a112da3ba487a1e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
