name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d7ed1b369e8f126a45f31ff69274334793e6bc21f40ecf17192dce3dd028df4"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
