name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cbd77d68221b011babe80d965427dcb1ec3b441821353342d6410f282b32b9d"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
