name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39cf96b44a874a81d972eaab55c6392ffc70023ae540b84621d6f67b24d8d4d2"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
