name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "904282a1c2e2bd18a277eac0188424b677e39d6c77dbd5a180fa682a3eaf6d91"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
