name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7d971c68ab660106775a883053df28dfbba224daf5a4690d88d97e5d93be252"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
