name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44518e116d8f9fb84b89f24fc331db5f46557ad453891a2f5bd4c3d484a7d257"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
