name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d114d30da4d4f7c70cf44dd7f965e6876ced767696ef4ac43edac06fe15a0ec"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
