name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be4c74e26215bc3f636bb3277ca96baa4a3c06849fb62d45c88030da142bd996"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
