name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3112f7461a45bf561ef01992bfd3c7f4fda1a8f179143687f817844a48ec18c8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
