name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b2a1793bd730a9a1d92a2d923714882b1353aaecb20f2b8495c189ecb3e2c1a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
