name = "S3Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7726a40a407a567aee0b72979d1eca435174ed8e5cec6960221c64910f36fd86"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
